apps/exercicios/urls.py
from django.urls import path, include
from .views import main_view, lista_exercicios, ranking, submeter_exercicio

app_name = "exercicios"

urlpatterns = [
    path("", main_view, name="main"),
    path("exercicios/", lista_exercicios, name='lista_exercicios'),
    path("<int:exercicio_id>/", submeter_exercicio, name="submeter"),
    path("ranking/", ranking, name='ranking'),
]

apps/ranking/urls.py
from django.urls import path
from .views import ranking

app_name = "ranking"

urlpatterns = [
    path("", ranking, name="ranking"),
]

apps/usuarios/urls.py
from django.urls import path
from .views import cadastrar_usuario, login_usuario, logout_usuario

app_name = "usuarios"

urlpatterns = [
    path("", login_usuario, name="login_usuario"),
    path("logout/", logout_usuario, name="logout_usuario"),
    path("cadastro/", cadastrar_usuario, name="cadastro_usuario"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios', include("apps.usuarios.urls")),
    path("exercicios/", include("apps.exercicios.urls",)),
    path("exercicios/" , include("apps.exercicios.urls")),
    path("ranking/", include("apps.ranking.urls")),
    path('', include('apps.usuarios.urls')),
]

templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameLoops</title>
    <link rel="stylesheet" href="{% static 'style/navbar.css' %}" />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="logo">
          <h1>GameLoops</h1>
        </div>

        <ul class="box-links">
          <li><a href="{% url 'exercicios:lista_exercicios' %}">Exercícios</a></li>
          <li><a href="{% url 'ranking:ranking' %}">Ranking</a></li>
        </ul>

        

        <div class="user-profile">
          <div class="user-stats">
            <p>❤️ {{ perfil.vidas }}</p>
            <p>⭐ {{ perfil.pontos }}</p>
            <p>🔥 {{ perfil.sequencia_dias }}</p>
          </div>
          
          <div class="user">
            <i class="bx bx-user"></i>
            <span>{{ user.username }}</span>
          </div>

          <a href="{% url 'usuarios:logout_usuario' %}">Logout</a>
        </div>
      </nav>
    </header>

    <div class="content">{% block content %} {% endblock %}</div>
  </body>
</html>